FROM node:22-bookworm-slim AS build
WORKDIR /app

COPY apps/frontend/package*.json ./
RUN npm ci
COPY apps/frontend/ ./
RUN npm run build

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=build /app ./
EXPOSE 3000
CMD ["npm", "run", "start"]
